(cl:defpackage zed_interfaces-msg
  (:use )
  (:export
   "<BOUNDINGBOX2DF>"
   "BOUNDINGBOX2DF"
   "<BOUNDINGBOX2DI>"
   "BOUNDINGBOX2DI"
   "<BOUNDINGBOX3D>"
   "BOUNDINGBOX3D"
   "<KEYPOINT2DF>"
   "KEYPOINT2DF"
   "<KEYPOINT2DI>"
   "KEYPOINT2DI"
   "<KEYPOINT3D>"
   "KEYPOINT3D"
   "<OBJECT>"
   "OBJECT"
   "<OBJECTSSTAMPED>"
   "OBJECTSSTAMPED"
   "<PLANESTAMPED>"
   "PLANESTAMPED"
   "<RGBDSENSORS>"
   "RGBDSENSORS"
   "<SKELETON2D>"
   "SKELETON2D"
   "<SKELETON3D>"
   "SKELETON3D"
  ))

