(cl:in-package zed_interfaces-msg)
(cl:export '(LABEL-VAL
          LABEL
          LABEL_ID-VAL
          LABEL_ID
          SUBLABEL-VAL
          SUBLABEL
          CONFIDENCE-VAL
          CONFIDENCE
          POSITION-VAL
          POSITION
          POSITION_COVARIANCE-VAL
          POSITION_COVARIANCE
          VELOCITY-VAL
          VELOCITY
          TRACKING_AVAILABLE-VAL
          TRACKING_AVAILABLE
          TRACKING_STATE-VAL
          TRACKING_STATE
          ACTION_STATE-VAL
          ACTION_STATE
          BOUNDING_BOX_2D-VAL
          BOUNDING_BOX_2D
          BOUNDING_BOX_3D-VAL
          BOUNDING_BOX_3D
          DIMENSIONS_3D-VAL
          DIMENSIONS_3D
          SKELETON_AVAILABLE-VAL
          SKELETON_AVAILABLE
          HEAD_BOUNDING_BOX_2D-VAL
          HEAD_BOUNDING_BOX_2D
          HEAD_BOUNDING_BOX_3D-VAL
          HEAD_BOUNDING_BOX_3D
          HEAD_POSITION-VAL
          HEAD_POSITION
          SKELETON_2D-VAL
          SKELETON_2D
          SKELETON_3D-VAL
          SKELETON_3D
))