// Generated by gencpp from file zed_interfaces/BoundingBox3D.msg
// DO NOT EDIT!


#ifndef ZED_INTERFACES_MESSAGE_BOUNDINGBOX3D_H
#define ZED_INTERFACES_MESSAGE_BOUNDINGBOX3D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <zed_interfaces/Keypoint3D.h>

namespace zed_interfaces
{
template <class ContainerAllocator>
struct BoundingBox3D_
{
  typedef BoundingBox3D_<ContainerAllocator> Type;

  BoundingBox3D_()
    : corners()  {
    }
  BoundingBox3D_(const ContainerAllocator& _alloc)
    : corners()  {
  (void)_alloc;
      corners.assign( ::zed_interfaces::Keypoint3D_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::zed_interfaces::Keypoint3D_<ContainerAllocator> , 8>  _corners_type;
  _corners_type corners;





  typedef boost::shared_ptr< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox3D_

typedef ::zed_interfaces::BoundingBox3D_<std::allocator<void> > BoundingBox3D;

typedef boost::shared_ptr< ::zed_interfaces::BoundingBox3D > BoundingBox3DPtr;
typedef boost::shared_ptr< ::zed_interfaces::BoundingBox3D const> BoundingBox3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zed_interfaces::BoundingBox3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zed_interfaces::BoundingBox3D_<ContainerAllocator1> & lhs, const ::zed_interfaces::BoundingBox3D_<ContainerAllocator2> & rhs)
{
  return lhs.corners == rhs.corners;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zed_interfaces::BoundingBox3D_<ContainerAllocator1> & lhs, const ::zed_interfaces::BoundingBox3D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zed_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3750b81144ba1b26f88ce23eeb4efd34";
  }

  static const char* value(const ::zed_interfaces::BoundingBox3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3750b81144ba1b26ULL;
  static const uint64_t static_value2 = 0xf88ce23eeb4efd34ULL;
};

template<class ContainerAllocator>
struct DataType< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zed_interfaces/BoundingBox3D";
  }

  static const char* value(const ::zed_interfaces::BoundingBox3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#      1 ------- 2\n"
"#     /.        /|\n"
"#    0 ------- 3 |\n"
"#    | .       | |\n"
"#    | 5.......| 6\n"
"#    |.        |/\n"
"#    4 ------- 7\n"
"zed_interfaces/Keypoint3D[8] corners\n"
"\n"
"================================================================================\n"
"MSG: zed_interfaces/Keypoint3D\n"
"float32[3] kp\n"
;
  }

  static const char* value(const ::zed_interfaces::BoundingBox3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.corners);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zed_interfaces::BoundingBox3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zed_interfaces::BoundingBox3D_<ContainerAllocator>& v)
  {
    s << indent << "corners[]" << std::endl;
    for (size_t i = 0; i < v.corners.size(); ++i)
    {
      s << indent << "  corners[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::zed_interfaces::Keypoint3D_<ContainerAllocator> >::stream(s, indent + "    ", v.corners[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZED_INTERFACES_MESSAGE_BOUNDINGBOX3D_H
