// Generated by gencpp from file zed_interfaces/BoundingBox2Di.msg
// DO NOT EDIT!


#ifndef ZED_INTERFACES_MESSAGE_BOUNDINGBOX2DI_H
#define ZED_INTERFACES_MESSAGE_BOUNDINGBOX2DI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <zed_interfaces/Keypoint2Di.h>

namespace zed_interfaces
{
template <class ContainerAllocator>
struct BoundingBox2Di_
{
  typedef BoundingBox2Di_<ContainerAllocator> Type;

  BoundingBox2Di_()
    : corners()  {
    }
  BoundingBox2Di_(const ContainerAllocator& _alloc)
    : corners()  {
  (void)_alloc;
      corners.assign( ::zed_interfaces::Keypoint2Di_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::zed_interfaces::Keypoint2Di_<ContainerAllocator> , 4>  _corners_type;
  _corners_type corners;





  typedef boost::shared_ptr< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox2Di_

typedef ::zed_interfaces::BoundingBox2Di_<std::allocator<void> > BoundingBox2Di;

typedef boost::shared_ptr< ::zed_interfaces::BoundingBox2Di > BoundingBox2DiPtr;
typedef boost::shared_ptr< ::zed_interfaces::BoundingBox2Di const> BoundingBox2DiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zed_interfaces::BoundingBox2Di_<ContainerAllocator1> & lhs, const ::zed_interfaces::BoundingBox2Di_<ContainerAllocator2> & rhs)
{
  return lhs.corners == rhs.corners;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zed_interfaces::BoundingBox2Di_<ContainerAllocator1> & lhs, const ::zed_interfaces::BoundingBox2Di_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zed_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48f8f53e85eafba49fb9648f6258d114";
  }

  static const char* value(const ::zed_interfaces::BoundingBox2Di_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48f8f53e85eafba4ULL;
  static const uint64_t static_value2 = 0x9fb9648f6258d114ULL;
};

template<class ContainerAllocator>
struct DataType< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zed_interfaces/BoundingBox2Di";
  }

  static const char* value(const ::zed_interfaces::BoundingBox2Di_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#      0 ------- 1\n"
"#      |         |\n"
"#      |         |\n"
"#      |         |\n"
"#      3 ------- 2\n"
"zed_interfaces/Keypoint2Di[4] corners\n"
"\n"
"================================================================================\n"
"MSG: zed_interfaces/Keypoint2Di\n"
"uint32[2] kp\n"
;
  }

  static const char* value(const ::zed_interfaces::BoundingBox2Di_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.corners);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox2Di_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zed_interfaces::BoundingBox2Di_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zed_interfaces::BoundingBox2Di_<ContainerAllocator>& v)
  {
    s << indent << "corners[]" << std::endl;
    for (size_t i = 0; i < v.corners.size(); ++i)
    {
      s << indent << "  corners[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::zed_interfaces::Keypoint2Di_<ContainerAllocator> >::stream(s, indent + "    ", v.corners[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZED_INTERFACES_MESSAGE_BOUNDINGBOX2DI_H
