// Generated by gencpp from file zed_interfaces/save_area_memory.msg
// DO NOT EDIT!


#ifndef ZED_INTERFACES_MESSAGE_SAVE_AREA_MEMORY_H
#define ZED_INTERFACES_MESSAGE_SAVE_AREA_MEMORY_H

#include <ros/service_traits.h>


#include <zed_interfaces/save_area_memoryRequest.h>
#include <zed_interfaces/save_area_memoryResponse.h>


namespace zed_interfaces
{

struct save_area_memory
{

typedef save_area_memoryRequest Request;
typedef save_area_memoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct save_area_memory
} // namespace zed_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zed_interfaces::save_area_memory > {
  static const char* value()
  {
    return "c8b71483aabdfc117f6a0d5ed8a98ab9";
  }

  static const char* value(const ::zed_interfaces::save_area_memory&) { return value(); }
};

template<>
struct DataType< ::zed_interfaces::save_area_memory > {
  static const char* value()
  {
    return "zed_interfaces/save_area_memory";
  }

  static const char* value(const ::zed_interfaces::save_area_memory&) { return value(); }
};


// service_traits::MD5Sum< ::zed_interfaces::save_area_memoryRequest> should match
// service_traits::MD5Sum< ::zed_interfaces::save_area_memory >
template<>
struct MD5Sum< ::zed_interfaces::save_area_memoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::save_area_memory >::value();
  }
  static const char* value(const ::zed_interfaces::save_area_memoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::save_area_memoryRequest> should match
// service_traits::DataType< ::zed_interfaces::save_area_memory >
template<>
struct DataType< ::zed_interfaces::save_area_memoryRequest>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::save_area_memory >::value();
  }
  static const char* value(const ::zed_interfaces::save_area_memoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zed_interfaces::save_area_memoryResponse> should match
// service_traits::MD5Sum< ::zed_interfaces::save_area_memory >
template<>
struct MD5Sum< ::zed_interfaces::save_area_memoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::save_area_memory >::value();
  }
  static const char* value(const ::zed_interfaces::save_area_memoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::save_area_memoryResponse> should match
// service_traits::DataType< ::zed_interfaces::save_area_memory >
template<>
struct DataType< ::zed_interfaces::save_area_memoryResponse>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::save_area_memory >::value();
  }
  static const char* value(const ::zed_interfaces::save_area_memoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZED_INTERFACES_MESSAGE_SAVE_AREA_MEMORY_H
