// Generated by gencpp from file zed_interfaces/save_3d_map.msg
// DO NOT EDIT!


#ifndef ZED_INTERFACES_MESSAGE_SAVE_3D_MAP_H
#define ZED_INTERFACES_MESSAGE_SAVE_3D_MAP_H

#include <ros/service_traits.h>


#include <zed_interfaces/save_3d_mapRequest.h>
#include <zed_interfaces/save_3d_mapResponse.h>


namespace zed_interfaces
{

struct save_3d_map
{

typedef save_3d_mapRequest Request;
typedef save_3d_mapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct save_3d_map
} // namespace zed_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zed_interfaces::save_3d_map > {
  static const char* value()
  {
    return "6b30b06d24a8a3ccaaea817409144337";
  }

  static const char* value(const ::zed_interfaces::save_3d_map&) { return value(); }
};

template<>
struct DataType< ::zed_interfaces::save_3d_map > {
  static const char* value()
  {
    return "zed_interfaces/save_3d_map";
  }

  static const char* value(const ::zed_interfaces::save_3d_map&) { return value(); }
};


// service_traits::MD5Sum< ::zed_interfaces::save_3d_mapRequest> should match
// service_traits::MD5Sum< ::zed_interfaces::save_3d_map >
template<>
struct MD5Sum< ::zed_interfaces::save_3d_mapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::save_3d_map >::value();
  }
  static const char* value(const ::zed_interfaces::save_3d_mapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::save_3d_mapRequest> should match
// service_traits::DataType< ::zed_interfaces::save_3d_map >
template<>
struct DataType< ::zed_interfaces::save_3d_mapRequest>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::save_3d_map >::value();
  }
  static const char* value(const ::zed_interfaces::save_3d_mapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zed_interfaces::save_3d_mapResponse> should match
// service_traits::MD5Sum< ::zed_interfaces::save_3d_map >
template<>
struct MD5Sum< ::zed_interfaces::save_3d_mapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::save_3d_map >::value();
  }
  static const char* value(const ::zed_interfaces::save_3d_mapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::save_3d_mapResponse> should match
// service_traits::DataType< ::zed_interfaces::save_3d_map >
template<>
struct DataType< ::zed_interfaces::save_3d_mapResponse>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::save_3d_map >::value();
  }
  static const char* value(const ::zed_interfaces::save_3d_mapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZED_INTERFACES_MESSAGE_SAVE_3D_MAP_H
